services:
  postgres:
    image: postgres:16-alpine
    container_name: venue_db
    environment:
      POSTGRES_DB: venue
      POSTGRES_USER: venue_user
      POSTGRES_PASSWORD: venue_pass
    ports:
      - '5432:5432'
    volumes:
      - venue_postgres_data:/var/lib/postgresql/data

volumes:
  venue_postgres_data:
